name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install pipenv
        run: |
            pip install pipenv
        
      - name: Install dependencies
        run: |
            pipenv install --dev
        working-directory: ./backend

      - name: Run linting
        run: |
            pipenv run lint
        working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install pipenv
        run: |
          pip install pipenv
      
      - name: Install dependencies
        run: |
            pipenv install --dev
        working-directory: ./backend

      - name: Run linting
        run: |
            pipenv run test
        working-directory: ./backend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --tag mp-backend:latest .
      
      - name: Run the image
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend
      
      - name: Check the running application
        run: |
          expected_output='{"movies":[{"id":"123","title":"Top Gun: Maverick"},{"id":"456","title":"Sonic the Hedgehog"},{"id":"789","title":"A Quiet Place"}]}'
          actual_output=$(curl -s http://localhost:5000/movies)
          echo "Expected: $expected_output"
          echo "Actual: $actual_output"
          if [ "$actual_output" != "$expected_output" ]; then
            echo "Output does not match expected value"
            exit 1
          fi
          echo "Output matches expected value"
      
      - name: Stop the application
        run: docker stop mp-backend
